name: lint
on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix run nixpkgs#statix -- check .
      - run: nix run nixpkgs#deadnix -- --no-lambda-pattern-names --fail .
      - run: nix run nixpkgs#shellcheck -- -S warning -e SC2154 sketchybar/plugins/*.sh
