#!/usr/bin/env bash
# vault-recent: regenerate the marked block in recently.md with the N most
# recently modified *shareable* notes. deterministic from vault mtimes, so every
# host produces the same block; writes only on change to avoid Sync churn.
set -euo pipefail

VAULT="${1:-$HOME/vault}"
TARGET="$VAULT/recently.md"
N=8
START="<!-- PLUSH:RECENT:START"
END="<!-- PLUSH:RECENT:END -->"

# folders/files that are noise in a "recently touched" feed (not privacy; this is
# a curation surface). everything else in the vault is fair game.
EXCLUDE_RE='^\./(\.obsidian|\.archive|\.trash|templates|reference/attachments|daily|inbox|shopping)/|^\./(home|welcome|now|recently|plan|guide)\.md$'

cd "$VAULT"

# gather: mtime<TAB>relpath for every md, drop excludes, newest first, take N
mapfile -t rows < <(
  find . -name '*.md' -not -path '*/.git/*' -printf '%T@\t%p\n' 2>/dev/null \
    | grep -Ev "$(printf '%s' "$EXCLUDE_RE" | sed 's#\t#\\t#g')" 2>/dev/null || true
)

# the grep above is finicky with the alternation on paths; filter in bash instead
build_cards() {
  local count=0
  printf '%s\n' "$START -- everything between these markers is regenerated by vault-recent -->"
  printf '<div class="cards">\n'
  while IFS=$'\t' read -r mtime path; do
    [ -n "${path:-}" ] || continue
    case "$path" in
      ./.obsidian/*|./.archive*|./.trash/*|./templates/*|./reference/attachments/*|./daily/*|./inbox/*|./shopping/*) continue;;
      ./home.md|./welcome.md|./now.md|./recently.md|./plan.md|./guide.md|./moc-*.md) continue;;
    esac
    # title: first "# " heading, stripped of leading symbols/emoji; fallback slug
    local rel title url date
    rel="${path#./}"
    title="$(grep -m1 '^# ' "$path" 2>/dev/null | sed -E 's/^#\s+//; s/^[^[:alnum:]]+//' || true)"
    [ -n "$title" ] || title="$(basename "$rel" .md)"
    title="${title%% :: *}"; title="${title%% · *}"; title="${title%% — *}"
    url="/${rel%.md}"
    date="$(date -d "@${mtime%.*}" '+%d %b' | tr 'A-Z' 'a-z')"
    printf '  <a class="card" href="%s"><b>%s →</b><br><small>%s</small></a>\n' "$url" "$title" "$date"
    count=$((count+1))
    [ "$count" -ge "$N" ] && break
  done < <(printf '%s\n' "${rows[@]}" | sort -rn)
  printf '</div>\n'
  printf '%s\n' "$END"
}

new_block="$(build_cards)"

# splice between markers, write only if changed
tmp="$(mktemp)"
awk -v blk="$new_block" '
  $0 ~ /PLUSH:RECENT:START/ { print blk; skip=1; next }
  $0 ~ /PLUSH:RECENT:END/   { skip=0; next }
  !skip { print }
' "$TARGET" > "$tmp"

if ! cmp -s "$tmp" "$TARGET"; then
  cat "$tmp" > "$TARGET"
  echo "vault-recent: updated $TARGET"
else
  echo "vault-recent: no change"
fi
rm -f "$tmp"
