{
  lib,
  config,
  pkgs,
  ...
}:
let
  cfg = config.rice.example;

  # fallback so standalone eval works without the theme module
  theme = config.rice.theme or { };
  accentHex = theme.accentHex or "#c6a0f6";
in
{
  options.rice.example = {
    enable = lib.mkEnableOption "the example feature";

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.hello;
      defaultText = lib.literalExpression "pkgs.hello";
      description = "The package this feature installs. Swap for the real one.";
    };

    accent = lib.mkOption {
      type = lib.types.str;
      default = accentHex;
      defaultText = lib.literalExpression "config.rice.theme.accentHex";
      description = ''
        Accent colour as #rrggbb. Defaults to the rice theme accent
        (config.rice.theme.accentHex) so it follows the global palette.
      '';
    };

    extraSettings = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      example = lib.literalExpression ''{ key = "value"; }'';
      description = "Free-form extra settings merged into the generated config.";
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages = [ cfg.package ];

    xdg.configFile."rice-example/config.ini".text = ''
      ; generated by rice.example, do not edit by hand
      accent = ${cfg.accent}
      ${lib.concatStringsSep "\n" (
        lib.mapAttrsToList (name: value: "${name} = ${value}") cfg.extraSettings
      )}
    '';
  };
}
